development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:0dab10803276b43479c52642c4bac252@soldierfish.redistogo.com:10799/
  channel_prefix: homz_direct_production
